### ISSUE TITLE
Review introductory git course

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/introductory_grad_school_git_course#48]
Introductory Git/GitHub course

- [x] #51
- [x] #52
- [x] #53
- [x] #54
- [x] #55
- [x] #56
- [x] #57

May need to check accessibility/visibility of course since SSO

**Comment by dc2917** [comment]
> Emphasize knowing bash/terminal as requirement - or point to online resources about it

Check that set-up instructions clearly state this

> When explaining GitKraken, mention they can use GitHub Desktop, just buttons and functionality will be different. Clarify that GitKraken is cross-platform, and that is why we are using it
Mention in the setup that GitKraken will be installed later on, so they are ready for it
Create a GitHub account during the setup (nothing else). PAT configuration, if needed will be done later

Again, in set-up instructions say something like "A GitHub account will be required for the course. You may wish to create this ahead of time." Same for PAT. And then something like "GitKraken will be demoed during the course. You may wish to download and install this ahead of time. Alternatively, if you already use a graphical interface to git, ..."
