### ISSUE TITLE
Update main pages, including the README, index etc. to reflect new course title, content and aims

### ISSUE THREAD

**Issue by dandavies99** [ImperialCollegeLondon/introductory_grad_school_git_course#6]

**Comment by dc2917** [comment]
Just looking at the handouts. The handout for lesson 1 contains a git command cheat sheet, which contains branch, checkout and merge commands. These concepts are now only covered in the intermediate course, but I think it's still useful to have a place with all of these. Maybe I should just remove them from here and have a (more) complete cheat sheet in the intermediate course?
